### ISSUE TITLE
npm后不能使用

### ISSUE THREAD

**Issue by gs183900** [sex-pomelo/sex-pomelo#9]
/opt/homebrew/lib/node_modules/@sex-pomelo/sex-pomelo/lib/master/starter.js:13
  static pomelo = null;
                ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/@sex-pomelo/sex-pomelo/lib/util/appUtil.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

请问是哪里操作不对？node版本：v10.24.0

**Comment by shudingbo** [comment]
node 版本有问题，不知道你是怎么安装的，建议用 v14.x 版本（最好直接用node源码装）.
> 前两天部署的时候也遇到了此问题，当时node环境是另外一个同事安装的（安装了6台，就只有一台出现了这个问题），不知道是什么问题，重新安装 node 环境后就OK 了。 按理说 static 语法，在 8.x 版本就支持了
